name: Random Cron
on:
  workflow_run:
    workflows: ["刷步数"]
    types:
      - completed
  workflow_dispatch:
  ############################################################
      days:
        description: '清理[X]天之前的Actions空间操作记录(可改)'
        required: true
        default: '3'
      rele:
        description: '保留[X]个Releases不被删除(可改)'
        required: true
        default: '10'
  ############################################################

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    if: github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：README
      - name: random cron
        run: |
          source cron_convert.sh
          echo "configed CRON_HOURS ${{ vars.CRON_HOURS }}"
          persist_execute_log ${{ github.event_name }} ${{ vars.CRON_HOURS }}
          git config user.name github-actions
          git config user.email github-actions@users.noreply.github.com
          git add .
          current=`TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S'`
          git commit -m "[${current}] random cron trigger by ${{ github.event_name }}"
          git push origin master
